"""Post-hoc threshold refit on the hand-written held-out set.

training/train.py's `_choose_thresholds` fits `defer`/`confirm` on the
template-derived test split it produces during training. That split is
optimistic: every example there was generated by the same process the model
trained on (different variant text, same templates), so it overstates
real-world accuracy by a wide margin.

This script does NOT retrain. It loads the already-trained model, scores
`eval/heldout.yaml` -- a hand-written set with zero corpus overlap with the
generated training data (see training/evaluate.py::check_heldout_overlap) --
and re-runs the SAME cost-minimisation logic (`_choose_thresholds`, imported
from training.train, never duplicated) over those held-out scores. It then
rewrites ONLY the `thresholds` block of models/manifest.json; weights,
temperature, labels, and seed are left exactly as training left them.

Usage:
    python -m training.fit_thresholds
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

# Allow `python training/fit_thresholds.py` as well as
# `python -m training.fit_thresholds`, matching training/train.py's own
# sys.path handling.
_ROOT_FOR_IMPORTS = Path(__file__).resolve().parent.parent
if str(_ROOT_FOR_IMPORTS) not in sys.path:
    sys.path.insert(0, str(_ROOT_FOR_IMPORTS))

import numpy as np

from training.evaluate import load_heldout
from training.train import CANDIDATE_THRESHOLDS, LABELS, MISCLASSIFY_COST, _choose_thresholds

ROOT = Path(__file__).parent.parent
MODEL_DIR = ROOT / "models"
MANIFEST_PATH = MODEL_DIR / "manifest.json"

# The cost function _choose_thresholds minimises prices a deferral purely as
# a wrong-answer-avoided (1.0 per deferral vs. MISCLASSIFY_COST for a
# confidently wrong answer) -- it has no term for user patience. Under Task
# F's two-strike policy a deferral below `defer` is cheap in money (a free
# local re-prompt, not an API call) but NOT free in patience: an assistant
# that says "say that again, sugar?" to a third or more of everything you
# say stops feeling reliable, however good that threshold looks on the cost
# curve alone. 0.30 is the line: below it the assistant re-prompts
# occasionally; above it, re-prompting becomes the dominant experience.
MAX_REPROMPT_RATE = 0.30


def _probabilities_from_predictions(rows: list[tuple[int, float]],
                                    n_labels: int) -> np.ndarray:
    """Synthesize a probabilities matrix whose per-row argmax/max are
    exactly the given (predicted_index, confidence) pairs. `_choose_thresholds`
    reads only those two derived values off `probabilities` -- see its own
    docstring -- so this reproduces exactly what OnnxClassifier.classify
    reported without needing its internal softmax vector (which the runtime
    classifier does not expose, by design -- see jarvis_nlu/model.py)."""
    probabilities = np.zeros((len(rows), n_labels))
    for row, (predicted_index, confidence) in enumerate(rows):
        remainder = (1.0 - confidence) / (n_labels - 1)
        probabilities[row, :] = remainder
        probabilities[row, predicted_index] = confidence
    return probabilities


def score_heldout(classifier) -> tuple[np.ndarray, np.ndarray]:
    """Classify every eval/heldout.yaml example. Returns (probabilities,
    labels) in the shape `_choose_thresholds` expects."""
    examples = load_heldout()
    rows: list[tuple[int, float]] = []
    label_indices: list[int] = []
    for example in examples:
        predicted_label, confidence = classifier.classify(example.text)
        rows.append((LABELS.index(predicted_label), confidence))
        label_indices.append(LABELS.index(example.intent))
    probabilities = _probabilities_from_predictions(rows, len(LABELS))
    return probabilities, np.array(label_indices)


def reprompt_rate_in_scope(probabilities: np.ndarray, labels: np.ndarray, defer: float) -> float:
    """Fraction of actual in-scope held-out examples that fall below
    `defer` -- i.e. the share of genuine (non-out-of-scope) requests that
    the two-strike policy would re-prompt on first strike. This is the
    quantity MAX_REPROMPT_RATE budgets: it deliberately excludes actual
    out-of-scope examples, since a low-confidence out-of-scope utterance
    was never answerable by lowering `defer` further -- it would only leak
    (see `rates_at`'s `leak_rate`), not get handled."""
    out_of_scope_index = LABELS.index("out_of_scope")
    confidence = probabilities.max(axis=1)
    in_scope = labels != out_of_scope_index
    n_in_scope = in_scope.sum()
    if not n_in_scope:
        return 0.0
    below = in_scope & (confidence < defer)
    return float(below.sum() / n_in_scope)


def choose_thresholds_constrained(
        probabilities: np.ndarray, labels: np.ndarray,
        max_reprompt_rate: float = MAX_REPROMPT_RATE) -> dict:
    """Task F fix: `_choose_thresholds`'s cost minimisation, constrained to
    only consider candidate `defer` values whose held-out in-scope
    re-prompt rate is at or under `max_reprompt_rate`. Reuses
    `_choose_thresholds` unchanged (via its `candidate_thresholds`
    parameter) rather than duplicating the cost formula -- only the
    candidate SET shrinks, the objective does not change.

    If no candidate threshold satisfies the constraint (which can only
    happen with a pathologically low `max_reprompt_rate`, or a model whose
    confidence never separates in-scope from out-of-scope), falls back to
    the plain unconstrained argmin and prints a loud warning -- the
    constraint is never silently dropped."""
    feasible = np.array([
        tau for tau in CANDIDATE_THRESHOLDS
        if reprompt_rate_in_scope(probabilities, labels, tau) <= max_reprompt_rate
    ])
    if len(feasible) == 0:
        print(f"WARNING: no candidate defer threshold keeps the held-out "
              f"in-scope re-prompt rate at or under {max_reprompt_rate:.1%} "
              f"-- falling back to the UNCONSTRAINED cost argmin (the "
              f"re-prompt-rate budget could not be satisfied and is being "
              f"ignored, not silently dropped).")
        return _choose_thresholds(probabilities, labels)
    return _choose_thresholds(probabilities, labels, candidate_thresholds=feasible)


def trade_off_table(probabilities: np.ndarray, labels: np.ndarray,
                    taus: list[float]) -> dict[float, dict[str, float]]:
    """The legibility table: for each candidate tau, the re-prompt rate
    (the new budgeted quantity), the confidently-wrong-in-scope rate (the
    original cost-function failure), and the out-of-scope-LLM rate (share
    of ALL held-out turns that escalate immediately as confident
    out-of-scope) -- so a human can see the whole trade before moving the
    knob."""
    out_of_scope_index = LABELS.index("out_of_scope")
    predicted = probabilities.argmax(axis=1)
    confidence = probabilities.max(axis=1)
    in_scope = labels != out_of_scope_index
    n_total = max(len(labels), 1)
    n_in_scope = in_scope.sum()

    table = {}
    for tau in taus:
        answered = confidence >= tau
        confidently_wrong = (in_scope & answered & (predicted != labels)).sum()
        out_of_scope_llm = ((predicted == out_of_scope_index) & answered).sum()
        table[tau] = {
            "reprompt_rate": reprompt_rate_in_scope(probabilities, labels, tau),
            "confidently_wrong_rate": (confidently_wrong / n_in_scope
                                       if n_in_scope else 0.0),
            "out_of_scope_llm_rate": out_of_scope_llm / n_total,
        }
    return table


def rates_at(probabilities: np.ndarray, labels: np.ndarray, defer: float) -> dict[str, float]:
    """Deferral / confidently-wrong / leak rates at a given defer threshold,
    matching the definitions training/evaluate.py::score and
    training/train.py::_choose_thresholds already use, so these numbers are
    directly comparable to `python -m training.evaluate --heldout` output."""
    out_of_scope_index = LABELS.index("out_of_scope")
    predicted = probabilities.argmax(axis=1)
    confidence = probabilities.max(axis=1)
    in_scope = labels != out_of_scope_index
    out_of_scope = ~in_scope
    answered = confidence >= defer

    deferred_in_scope = in_scope & (~answered | (predicted == out_of_scope_index))
    confidently_wrong = in_scope & answered & (predicted != labels)
    leaked = out_of_scope & answered & (predicted != out_of_scope_index)

    return {
        "deferral_rate": deferred_in_scope.sum() / in_scope.sum() if in_scope.sum() else 0.0,
        "confidently_wrong_rate": (confidently_wrong.sum() / in_scope.sum()
                                   if in_scope.sum() else 0.0),
        "leak_rate": leaked.sum() / out_of_scope.sum() if out_of_scope.sum() else 0.0,
    }


def policy_split(probabilities: np.ndarray, defer: float) -> dict[str, float]:
    """What the router actually DOES at this threshold, regardless of
    whether it's right -- the three-way split Task F's two-strike policy
    acts on: handled locally, confidently out-of-scope (genuinely needs the
    LLM), or merely unsure (a free re-prompt under Task F, not an API
    call). Unlike `rates_at`, this never looks at ground truth."""
    out_of_scope_index = LABELS.index("out_of_scope")
    predicted = probabilities.argmax(axis=1)
    confidence = probabilities.max(axis=1)
    n_total = max(len(predicted), 1)

    handled_locally = (predicted != out_of_scope_index) & (confidence >= defer)
    confident_out_of_scope = (predicted == out_of_scope_index) & (confidence >= defer)
    unsure = confidence < defer

    return {
        "handled_locally": handled_locally.sum() / n_total,
        "confident_out_of_scope": confident_out_of_scope.sum() / n_total,
        "unsure": unsure.sum() / n_total,
    }


def main() -> None:
    from jarvis_nlu.model import OnnxClassifier

    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    before = manifest["thresholds"]

    classifier = OnnxClassifier(MODEL_DIR)
    probabilities, labels = score_heldout(classifier)
    # Constrained, not the raw cost argmin: see MAX_REPROMPT_RATE's comment
    # -- the cost function alone has no term for user patience and, left
    # unconstrained, picks a defer so high that ~44% of turns get
    # re-prompted.
    after = choose_thresholds_constrained(probabilities, labels)

    # _choose_thresholds floors confirm at defer + CONFIRM_MARGIN but caps it
    # at 0.99, so that margin is not guaranteed when defer itself lands
    # above 0.89 -- the invariant that must never break is the strict
    # inequality (an empty [defer, confirm) band lets a destructive intent
    # execute without ever asking), not the exact margin.
    assert after["confirm"] > after["defer"], (
        "confirmation band collapsed to empty or inverted -- refusing to "
        "write a manifest that would let a destructive intent execute "
        "without ever asking")

    manifest["thresholds"] = after
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    before_rates = rates_at(probabilities, labels, before["defer"])
    after_rates = rates_at(probabilities, labels, after["defer"])
    after_split = policy_split(probabilities, after["defer"])
    after_reprompt_rate = reprompt_rate_in_scope(probabilities, labels, after["defer"])

    print(f"MISCLASSIFY_COST = {MISCLASSIFY_COST}  (tunable -- higher penalises a "
          f"confidently-wrong local answer more, and pushes defer up)")
    print(f"MAX_REPROMPT_RATE = {MAX_REPROMPT_RATE:.0%}  (tunable -- a budget on held-out "
          f"in-scope re-prompt rate; the constraint the cost function alone ignores)")
    print()
    print(f"before (template-split fit): defer={before['defer']} confirm={before['confirm']}")
    print(f"  on held-out: deferral={before_rates['deferral_rate']:.1%} "
          f"confidently_wrong={before_rates['confidently_wrong_rate']:.1%} "
          f"leak={before_rates['leak_rate']:.1%}")
    print()
    print(f"after (held-out, constrained cost-argmin): "
          f"defer={after['defer']} confirm={after['confirm']}")
    print(f"  on held-out: deferral={after_rates['deferral_rate']:.1%} "
          f"confidently_wrong={after_rates['confidently_wrong_rate']:.1%} "
          f"leak={after_rates['leak_rate']:.1%} "
          f"reprompt_rate_in_scope={after_reprompt_rate:.1%}")
    print(f"  router policy split: handled_locally={after_split['handled_locally']:.1%} "
          f"confident_out_of_scope={after_split['confident_out_of_scope']:.1%} "
          f"unsure={after_split['unsure']:.1%}")
    print()
    print("Trade-off table (held-out):")
    print(f"  {'defer':>7} {'reprompt_rate':>14} {'confidently_wrong':>18} "
          f"{'out_of_scope_llm':>17}")
    report_taus = sorted({0.70, 0.75, 0.80, 0.83, 0.85, 0.90, 0.93, after["defer"]})
    table = trade_off_table(probabilities, labels, report_taus)
    for tau in report_taus:
        row = table[tau]
        marker = "  <- chosen" if abs(tau - after["defer"]) < 1e-9 else ""
        print(f"  {tau:>7.2f} {row['reprompt_rate']:>14.1%} "
              f"{row['confidently_wrong_rate']:>18.1%} "
              f"{row['out_of_scope_llm_rate']:>17.1%}{marker}")
    print()
    print(f"wrote {MANIFEST_PATH}")


if __name__ == "__main__":
    main()
