"""Post-hoc threshold refit on the hand-written held-out set.

training/train.py's `_choose_thresholds` fits `defer`/`confirm` on the
template-derived test split it produces during training. That split is
optimistic: every example there was generated by the same process the model
trained on (different variant text, same templates), so it overstates
real-world accuracy by a wide margin.

This script does NOT retrain. It loads the already-trained model, scores
`eval/heldout.yaml` -- a hand-written set with zero corpus overlap with the
generated training data (see training/evaluate.py::check_heldout_overlap) --
and re-runs the SAME cost-minimisation logic (`_choose_thresholds`, imported
from training.train, never duplicated) over those held-out scores. It then
rewrites ONLY the `thresholds` block of models/manifest.json; weights,
temperature, labels, and seed are left exactly as training left them.

Usage:
    python -m training.fit_thresholds
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

# Allow `python training/fit_thresholds.py` as well as
# `python -m training.fit_thresholds`, matching training/train.py's own
# sys.path handling.
_ROOT_FOR_IMPORTS = Path(__file__).resolve().parent.parent
if str(_ROOT_FOR_IMPORTS) not in sys.path:
    sys.path.insert(0, str(_ROOT_FOR_IMPORTS))

import numpy as np

from training.evaluate import load_heldout
from training.train import LABELS, MISCLASSIFY_COST, _choose_thresholds

ROOT = Path(__file__).parent.parent
MODEL_DIR = ROOT / "models"
MANIFEST_PATH = MODEL_DIR / "manifest.json"


def _probabilities_from_predictions(rows: list[tuple[int, float]],
                                    n_labels: int) -> np.ndarray:
    """Synthesize a probabilities matrix whose per-row argmax/max are
    exactly the given (predicted_index, confidence) pairs. `_choose_thresholds`
    reads only those two derived values off `probabilities` -- see its own
    docstring -- so this reproduces exactly what OnnxClassifier.classify
    reported without needing its internal softmax vector (which the runtime
    classifier does not expose, by design -- see jarvis_nlu/model.py)."""
    probabilities = np.zeros((len(rows), n_labels))
    for row, (predicted_index, confidence) in enumerate(rows):
        remainder = (1.0 - confidence) / (n_labels - 1)
        probabilities[row, :] = remainder
        probabilities[row, predicted_index] = confidence
    return probabilities


def score_heldout(classifier) -> tuple[np.ndarray, np.ndarray]:
    """Classify every eval/heldout.yaml example. Returns (probabilities,
    labels) in the shape `_choose_thresholds` expects."""
    examples = load_heldout()
    rows: list[tuple[int, float]] = []
    label_indices: list[int] = []
    for example in examples:
        predicted_label, confidence = classifier.classify(example.text)
        rows.append((LABELS.index(predicted_label), confidence))
        label_indices.append(LABELS.index(example.intent))
    probabilities = _probabilities_from_predictions(rows, len(LABELS))
    return probabilities, np.array(label_indices)


def rates_at(probabilities: np.ndarray, labels: np.ndarray, defer: float) -> dict[str, float]:
    """Deferral / confidently-wrong / leak rates at a given defer threshold,
    matching the definitions training/evaluate.py::score and
    training/train.py::_choose_thresholds already use, so these numbers are
    directly comparable to `python -m training.evaluate --heldout` output."""
    out_of_scope_index = LABELS.index("out_of_scope")
    predicted = probabilities.argmax(axis=1)
    confidence = probabilities.max(axis=1)
    in_scope = labels != out_of_scope_index
    out_of_scope = ~in_scope
    answered = confidence >= defer

    deferred_in_scope = in_scope & (~answered | (predicted == out_of_scope_index))
    confidently_wrong = in_scope & answered & (predicted != labels)
    leaked = out_of_scope & answered & (predicted != out_of_scope_index)

    return {
        "deferral_rate": deferred_in_scope.sum() / in_scope.sum() if in_scope.sum() else 0.0,
        "confidently_wrong_rate": (confidently_wrong.sum() / in_scope.sum()
                                   if in_scope.sum() else 0.0),
        "leak_rate": leaked.sum() / out_of_scope.sum() if out_of_scope.sum() else 0.0,
    }


def policy_split(probabilities: np.ndarray, defer: float) -> dict[str, float]:
    """What the router actually DOES at this threshold, regardless of
    whether it's right -- the three-way split Task F's two-strike policy
    acts on: handled locally, confidently out-of-scope (genuinely needs the
    LLM), or merely unsure (a free re-prompt under Task F, not an API
    call). Unlike `rates_at`, this never looks at ground truth."""
    out_of_scope_index = LABELS.index("out_of_scope")
    predicted = probabilities.argmax(axis=1)
    confidence = probabilities.max(axis=1)
    n_total = max(len(predicted), 1)

    handled_locally = (predicted != out_of_scope_index) & (confidence >= defer)
    confident_out_of_scope = (predicted == out_of_scope_index) & (confidence >= defer)
    unsure = confidence < defer

    return {
        "handled_locally": handled_locally.sum() / n_total,
        "confident_out_of_scope": confident_out_of_scope.sum() / n_total,
        "unsure": unsure.sum() / n_total,
    }


def main() -> None:
    from jarvis_nlu.model import OnnxClassifier

    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    before = manifest["thresholds"]

    classifier = OnnxClassifier(MODEL_DIR)
    probabilities, labels = score_heldout(classifier)
    after = _choose_thresholds(probabilities, labels)

    # _choose_thresholds floors confirm at defer + CONFIRM_MARGIN but caps it
    # at 0.99, so that margin is not guaranteed when defer itself lands
    # above 0.89 -- the invariant that must never break is the strict
    # inequality (an empty [defer, confirm) band lets a destructive intent
    # execute without ever asking), not the exact margin.
    assert after["confirm"] > after["defer"], (
        "confirmation band collapsed to empty or inverted -- refusing to "
        "write a manifest that would let a destructive intent execute "
        "without ever asking")

    manifest["thresholds"] = after
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    before_rates = rates_at(probabilities, labels, before["defer"])
    after_rates = rates_at(probabilities, labels, after["defer"])
    after_split = policy_split(probabilities, after["defer"])

    print(f"MISCLASSIFY_COST = {MISCLASSIFY_COST}  (tunable -- higher penalises a "
          f"confidently-wrong local answer more, and pushes defer up)")
    print()
    print(f"before (template-split fit): defer={before['defer']} confirm={before['confirm']}")
    print(f"  on held-out: deferral={before_rates['deferral_rate']:.1%} "
          f"confidently_wrong={before_rates['confidently_wrong_rate']:.1%} "
          f"leak={before_rates['leak_rate']:.1%}")
    print()
    print(f"after (held-out cost-argmin): defer={after['defer']} confirm={after['confirm']}")
    print(f"  on held-out: deferral={after_rates['deferral_rate']:.1%} "
          f"confidently_wrong={after_rates['confidently_wrong_rate']:.1%} "
          f"leak={after_rates['leak_rate']:.1%}")
    print(f"  router policy split: handled_locally={after_split['handled_locally']:.1%} "
          f"confident_out_of_scope={after_split['confident_out_of_scope']:.1%} "
          f"unsure={after_split['unsure']:.1%}")
    print()
    print(f"wrote {MANIFEST_PATH}")


if __name__ == "__main__":
    main()
